# Generated by Django 6.0.3 on 2026-03-28 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_initial'),
        ('users', '0008_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProctorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('ended', 'Ended'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('terminations_count', models.PositiveIntegerField(default=0)),
                ('penalty_percent', models.PositiveIntegerField(default=0)),
                ('device_id', models.CharField(blank=True, max_length=128, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_sessions', to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_proctor_sessions', to='users.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizProctorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quizzes.quizproctorsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizProctorSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='quizzes.quizproctorsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quizproctorsession',
            index=models.Index(fields=['quiz', 'student', 'status'], name='quizzes_qui_quiz_id_091d26_idx'),
        ),
        migrations.AddIndex(
            model_name='quizproctorsession',
            index=models.Index(fields=['student', 'status'], name='quizzes_qui_student_cf79a7_idx'),
        ),
        migrations.AddIndex(
            model_name='quizproctorevent',
            index=models.Index(fields=['session', 'event_type'], name='quizzes_qui_session_03c912_idx'),
        ),
        migrations.AddIndex(
            model_name='quizproctorsnapshot',
            index=models.Index(fields=['session', 'created_at'], name='quizzes_qui_session_6f609e_idx'),
        ),
    ]
