# Generated by Django 6.0.3 on 2026-03-28 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizproctorsession_quizproctorevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='penalty_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='raw_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
