# Generated by Django 6.0.3 on 2026-03-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quizattempt_penalty_percent_quizattempt_raw_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ai_grade_on_submit',
            field=models.BooleanField(default=True),
        ),
    ]
