# Generated by Django 6.0.3 on 2026-03-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quiz_ai_grade_on_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizproctorsession',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proctor_sessions', to='quizzes.quizattempt'),
        ),
    ]
