# Generated by Django 6.0.3 on 2026-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quizproctorsession_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='security_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('strict', 'Strict')], default='normal', max_length=12),
        ),
    ]
