# Generated by Django 6.0.3 on 2026-04-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quiz_security_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
