# Generated by Django 6.0.3 on 2026-03-16 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='school_levels.schoollevel')),
            ],
            options={
                'ordering': ['school_level', 'name'],
                'indexes': [models.Index(fields=['school_level', 'name'], name='departments_school__850bb2_idx')],
            },
        ),
    ]
