"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR.parent, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-4i3l%&^q@@reiu7#m!hx$dr^kg7&me-1#@wqb4+(kx3fmrp4z@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'true').lower() == 'true'

_default_hosts = '127.0.0.1,localhost,192.168.55.132,192.168.55.115,0.0.0.0'
_raw_hosts = os.getenv('ALLOWED_HOSTS', '')
_raw_frontend_urls = os.getenv('FRONTEND_URLS', 'https://e-learning-scsit-web-app-frontend.vercel.app')
FRONTEND_URLS = [url.strip() for url in _raw_frontend_urls.split(',') if url.strip()]
ALLOWED_HOSTS = [
    host.strip()
    for host in f"{_default_hosts},{_raw_hosts}".split(',')
    if host.strip()
]
for url in FRONTEND_URLS:
    try:
        host = url.split('://', 1)[-1].split('/', 1)[0]
        if host and host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
    except Exception:
        continue


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    "rest_framework_simplejwt.token_blacklist",
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'cloudinary',
    'cloudinary_storage',
    'users',
    'departments',
    'year_levels',
    'sections',
    'subjects',
    'learning_materials',
    'assignments',
    'quizzes',
    'school_levels',
    'programs',
    'announcements',
    'chat',
    'notifications',
    'dashboard',
    'attendance',
]

CHAT_SERVER_TOKEN = os.getenv('CHAT_SERVER_TOKEN', '')
CHAT_SERVER_TARGET = os.getenv('CHAT_SERVER_TARGET', 'local').lower()
CHAT_SERVER_HTTP_LOCAL_URL = os.getenv('CHAT_SERVER_HTTP_LOCAL_URL', 'http://127.0.0.1:8080')
CHAT_SERVER_HTTP_REMOTE_URL = os.getenv('CHAT_SERVER_HTTP_REMOTE_URL', 'https://chat-server-2h01.onrender.com')
CHAT_SERVER_WS_LOCAL_URL = os.getenv('CHAT_SERVER_WS_LOCAL_URL', 'ws://127.0.0.1:8080/ws/chat/')
CHAT_SERVER_WS_REMOTE_URL = os.getenv('CHAT_SERVER_WS_REMOTE_URL', 'wss://chat-server-2h01.onrender.com/ws/chat/')
CHAT_SERVER_HTTP_URL = (
    CHAT_SERVER_HTTP_REMOTE_URL
    if CHAT_SERVER_TARGET in {'remote', 'online', 'render', 'production'}
    else CHAT_SERVER_HTTP_LOCAL_URL
)
CHAT_SERVER_WS_URL = (
    CHAT_SERVER_WS_REMOTE_URL
    if CHAT_SERVER_TARGET in {'remote', 'online', 'render', 'production'}
    else CHAT_SERVER_WS_LOCAL_URL
)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
         "users.authentication.CookieJWTAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'user': '300/min',
        'anon': '60/min',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
  
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'
ASGI_APPLICATION = 'main.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8081',
    'http://localhost:19006',
    'http://127.0.0.1:8081',
    'http://127.0.0.1:19006',
    'http://localhost:3000',
    'http://192.168.137.121:3000',
    'http://192.168.55.115:3000',
    'http://localhost:8080',
    'http://192.168.137.121:8080',
    'https://e-learning-scsit-web-app-frontend-seven.vercel.app',
]
for url in FRONTEND_URLS:
    if url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(url)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

_raw_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _raw_csrf_origins:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _raw_csrf_origins.split(',') if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = FRONTEND_URLS

# Security hardening (safe defaults in prod)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'same-origin'
SECURE_BROWSER_XSS_FILTER = True

SECURE_SSL_REDIRECT = (not DEBUG) and os.getenv('SECURE_SSL_REDIRECT', 'true').lower() == 'true'
SESSION_COOKIE_SECURE = (not DEBUG) and os.getenv('SESSION_COOKIE_SECURE', 'true').lower() == 'true'
CSRF_COOKIE_SECURE = (not DEBUG) and os.getenv('CSRF_COOKIE_SECURE', 'true').lower() == 'true'
SECURE_HSTS_SECONDS = 0 if DEBUG else int(os.getenv('SECURE_HSTS_SECONDS', '3600'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASE_TARGET = os.getenv('DATABASE_TARGET', 'local').lower()
REMOTE_DATABASE_URL = os.getenv('REMOTE_DATABASE_URL') or os.getenv('DATABASE_URL')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'capstone_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

if DATABASE_TARGET in {'remote', 'online', 'render', 'production'} and REMOTE_DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(
        default=REMOTE_DATABASE_URL,
        conn_max_age=int(os.getenv('DB_CONN_MAX_AGE', '600')),
        ssl_require=os.getenv('DB_SSL_REQUIRE', 'true').lower() == 'true',
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudinary (optional)
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', '')

# Online class (Jitsi)
JITSI_BASE_URL = os.getenv('JITSI_BASE_URL', 'https://meet.jit.si')

# Attendance (online class)
ATTENDANCE_LATE_AFTER_MINUTES = int(os.getenv('ATTENDANCE_LATE_AFTER_MINUTES', '10'))

if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
        'SECURE': True,
        'RESOURCE_TYPE': 'auto',
    }
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# AI grading (Gemini)
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-1.5-flash')
GEMINI_API_BASE = os.getenv('GEMINI_API_BASE', 'https://generativelanguage.googleapis.com/v1beta')

# OpenAI (optional)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4.1-mini')
OPENAI_API_BASE = os.getenv('OPENAI_API_BASE', 'https://api.openai.com/v1')

# PDF learning material styling
PDF_LOGO_PATH = os.getenv('PDF_LOGO_PATH', '')
PDF_HEADER_TEXT = os.getenv('PDF_HEADER_TEXT', 'Learning Materials Pack')
PDF_FOOTER_TEXT = os.getenv('PDF_FOOTER_TEXT', 'Generated by AI learning materials assistant')
PDF_FILENAME_TEMPLATE = os.getenv('PDF_FILENAME_TEMPLATE', '{subject}-{title}-{date}.pdf')

# Email (SMTP)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'SCSIT NEXUS <no-reply@scsitnexus.local>')

AUTH_USER_MODEL = 'users.CustomUser'
