# Generated by Django 6.0.3 on 2026-03-16 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('school_levels', '0001_initial'),
        ('sections', '0002_initial'),
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
        ('year_levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student'),
        ),
        migrations.AddField(
            model_name='sectionsubject',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='sectionsubject',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='sections.section'),
        ),
        migrations.AddField(
            model_name='sectionsubject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='school_levels.term'),
        ),
        migrations.AddField(
            model_name='grade',
            name='section_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.sectionsubject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(help_text='Program/Course/Strand this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='programs.program'),
        ),
        migrations.AddField(
            model_name='subject',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='year_levels.yearlevel'),
        ),
        migrations.AddField(
            model_name='sectionsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'section_subject')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['program', 'year_level'], name='subjects_su_program_a05183_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('program', 'year_level', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionsubject',
            unique_together={('section', 'subject', 'term')},
        ),
    ]
