# Generated by Django 6.0.3 on 2026-03-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
        ('users', '0002_alter_instructor_user_adminprofile_adviser_dean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsubject',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_subjects', to='users.adviser'),
        ),
        migrations.AlterField(
            model_name='sectionsubject',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_subjects', to='users.instructor'),
        ),
    ]
