# Generated by Django 6.0.3 on 2026-03-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_sectionsubject_adviser_and_more'),
        ('users', '0005_principal_department_alter_adviser_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='users.instructor'),
        ),
    ]
