# Generated by Django 6.0.3 on 2026-03-20 08:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_school_years(apps, schema_editor):
    SectionSubject = apps.get_model('subjects', 'SectionSubject')
    Grade = apps.get_model('subjects', 'Grade')

    for ss in SectionSubject.objects.select_related('term__school_year').all():
        if ss.term_id and ss.term.school_year_id:
            SectionSubject.objects.filter(id=ss.id).update(school_year_id=ss.term.school_year_id)

    for grade in Grade.objects.select_related('section_subject__school_year').all():
        if grade.section_subject_id and grade.section_subject.school_year_id:
            Grade.objects.filter(id=grade.id).update(school_year_id=grade.section_subject.school_year_id)


class Migration(migrations.Migration):

    dependencies = [
        ('school_levels', '0003_schoolyear_alter_term_school_year'),
        ('subjects', '0004_subject_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school_levels.schoolyear'),
        ),
        migrations.AddField(
            model_name='sectionsubject',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_subjects', to='school_levels.schoolyear'),
        ),
        migrations.RunPython(backfill_school_years, migrations.RunPython.noop),
    ]
