# Generated by Django 6.0.3 on 2026-04-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_grade_school_year_sectionsubject_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsubject',
            name='schedule_days',
            field=models.CharField(blank=True, help_text='e.g. Mon, Wed, Fri', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sectionsubject',
            name='schedule_time',
            field=models.CharField(blank=True, help_text='e.g. 8:00 AM - 9:30 AM', max_length=50, null=True),
        ),
    ]
