# Generated by Django 6.0.3 on 2026-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0003_learningmaterial_attachment_and_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='learning_materials/'),
        ),
    ]
