# Generated by Django 6.0.3 on 2026-03-23 06:42

import learning_materials.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0004_alter_learningmaterial_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, storage=learning_materials.storage.LearningMaterialStorage(), upload_to='learning_materials/'),
        ),
    ]
