# Generated by Django 6.0.3 on 2026-03-16 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(help_text='program | strand | grade', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='departments.department')),
            ],
            options={
                'ordering': ['department', 'name'],
                'indexes': [models.Index(fields=['department', 'name'], name='programs_pr_departm_21ba2d_idx')],
            },
        ),
    ]
