# Generated by Django 6.0.3 on 2026-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('assignment_submission', 'Assignment Submission'), ('quiz_submission', 'Quiz Submission')], max_length=32),
        ),
    ]
