# Generated by Django 6.0.3 on 2026-04-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('assignment_submission', 'Assignment Submission'), ('quiz_submission', 'Quiz Submission'), ('attendance', 'Attendance')], max_length=32),
        ),
    ]
