# Generated by Django 6.0.3 on 2026-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('lesson', 'Learning Material'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('assignment_submission', 'Assignment Submission'), ('quiz_submission', 'Quiz Submission'), ('attendance', 'Attendance'), ('online_class', 'Online Class')], max_length=32),
        ),
    ]
