# Generated by Django 6.0.3 on 2026-03-16 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_levels', to='programs.program')),
            ],
            options={
                'ordering': ['order_number'],
                'indexes': [models.Index(fields=['program', 'order_number'], name='year_levels_program_75c7f8_idx')],
            },
        ),
    ]
