# Generated by Django 6.0.3 on 2026-03-16 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_levels', '0001_initial'),
        ('sections', '0001_initial'),
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
        ('year_levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school_levels.term'),
        ),
        migrations.AddField(
            model_name='section',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='year_levels.yearlevel'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sections.section'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='sections.enrollment'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='section_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='subjects.sectionsubject'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['year_level', 'name'], name='sections_se_year_le_911507_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'section', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('enrollment', 'section_subject')},
        ),
    ]
