# Generated by Django 6.0.3 on 2026-03-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_adviser_alter_enrollment_status'),
        ('year_levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='year_levels.yearlevel'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='sections.section'),
        ),
    ]
