# Generated by Django 6.0.3 on 2026-03-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_enrollment_year_level_alter_enrollment_section'),
        ('subjects', '0004_subject_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='enrollments', through='sections.StudentSubject', to='subjects.sectionsubject'),
        ),
    ]
