# Generated by Django 6.0.3 on 2026-03-20 08:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_school_years(apps, schema_editor):
    Enrollment = apps.get_model('sections', 'Enrollment')
    Section = apps.get_model('sections', 'Section')
    StudentSubject = apps.get_model('sections', 'StudentSubject')
    SectionSubject = apps.get_model('subjects', 'SectionSubject')

    for enrollment in Enrollment.objects.select_related('term__school_year').all():
        if enrollment.term_id and enrollment.term.school_year_id:
            Enrollment.objects.filter(id=enrollment.id).update(school_year_id=enrollment.term.school_year_id)

    for section in Section.objects.all():
        school_year_id = None
        first_enrollment = Enrollment.objects.filter(section_id=section.id, term__school_year__isnull=False).select_related('term__school_year').first()
        if first_enrollment and first_enrollment.term and first_enrollment.term.school_year_id:
            school_year_id = first_enrollment.term.school_year_id
        else:
            first_ss = SectionSubject.objects.filter(section_id=section.id, term__school_year__isnull=False).select_related('term__school_year').first()
            if first_ss and first_ss.term and first_ss.term.school_year_id:
                school_year_id = first_ss.term.school_year_id
        if school_year_id:
            Section.objects.filter(id=section.id).update(school_year_id=school_year_id)

    for ss in StudentSubject.objects.select_related('section_subject__school_year').all():
        if ss.section_subject_id and ss.section_subject.school_year_id:
            StudentSubject.objects.filter(id=ss.id).update(school_year_id=ss.section_subject.school_year_id)


class Migration(migrations.Migration):

    dependencies = [
        ('school_levels', '0003_schoolyear_alter_term_school_year'),
        ('sections', '0005_enrollment_subjects'),
        ('subjects', '0005_grade_school_year_sectionsubject_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='school_levels.schoolyear'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='school_levels.schoolyear'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_subjects', to='school_levels.schoolyear'),
        ),
        migrations.RunPython(backfill_school_years, migrations.RunPython.noop),
    ]
