# Generated by Django 6.0.3 on 2026-03-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_enrollment_school_year_section_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
