# Generated by Django 6.0.3 on 2026-03-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroommember_cleared_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_room_id_3b6a31_idx',
            old_name='chat_chatme_room_id_05b860_idx',
        ),
        migrations.RenameIndex(
            model_name='chatreadreceipt',
            new_name='chat_chatre_room_id_c97717_idx',
            old_name='chat_chatre_room_id_2b2c6a_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chat_chatro_room_ty_67ddb3_idx',
            old_name='chat_chatro_room_ty_e6b83f_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroommember',
            new_name='chat_chatro_room_id_4b2bd0_idx',
            old_name='chat_chatro_room_id_8597d4_idx',
        ),
    ]
