# Generated by ChatGPT on 2026-04-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_name'),
        ('chat', '0005_rename_chat_chatme_room_id_05b860_idx_chat_chatme_room_id_3b6a31_idx_and_more'),
    ]

    operations = []
