# Generated by Django 6.0.3 on 2026-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollevel',
            name='level_type',
            field=models.CharField(choices=[('college', 'College'), ('junior_high', 'Junior High School'), ('senior_high', 'Senior High School')], default='college', max_length=20),
        ),
    ]
