# Generated by Django 6.0.3 on 2026-03-20 08:39

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_school_years(apps, schema_editor):
    Term = apps.get_model('school_levels', 'Term')
    SchoolYear = apps.get_model('school_levels', 'SchoolYear')

    def parse_years(value):
        try:
            parts = str(value).split('-')
            start_year = int(parts[0])
            end_year = int(parts[1]) if len(parts) > 1 else start_year + 1
            return start_year, end_year
        except Exception:
            return None, None

    for term in Term.objects.all():
        raw = getattr(term, 'school_year', None)
        if not raw:
            continue
        start_year, end_year = parse_years(raw)
        if not start_year:
            start_year = 2000
            end_year = 2001
        if not end_year:
            end_year = start_year + 1
        sy, _ = SchoolYear.objects.get_or_create(
            name=str(raw),
            defaults={
                'start_date': datetime.date(start_year, 1, 1),
                'end_date': datetime.date(end_year, 12, 31),
                'is_active': False,
            }
        )
        term.school_year_fk = sy
        term.save(update_fields=['school_year_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('school_levels', '0002_schoollevel_level_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., 2025-2026', max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='term',
            name='school_year_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='school_levels.schoolyear'),
        ),
        migrations.RunPython(backfill_school_years, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='term',
            name='school_year',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='school_year_fk',
            new_name='school_year',
        ),
    ]
