# Generated by Django 6.0.3 on 2026-03-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('users', '0002_alter_instructor_user_adminprofile_adviser_dean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='program',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='adviser',
                to='programs.program',
            ),
        ),
    ]
