# Generated by Django 6.0.3 on 2026-03-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('users', '0003_adviser_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='program',
            field=models.OneToOneField(blank=True, limit_choices_to={'department__school_level__level_type__in': ['junior_high', 'senior_high'], 'type__in': ['strand', 'grade']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adviser', to='programs.program'),
        ),
    ]
