# Generated by Django 6.0.3 on 2026-03-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('programs', '0001_initial'),
        ('users', '0004_alter_adviser_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principals', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='program',
            field=models.OneToOneField(blank=True, limit_choices_to={'type__in': ['Strand', 'Grade']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adviser', to='programs.program'),
        ),
    ]
