# Generated by Django 6.0.3 on 2026-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profiles/'),
        ),
    ]
