# Generated by Django 6.0.3 on 2026-04-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_online_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='join_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='provider',
            field=models.CharField(blank=True, default='jitsi', max_length=30),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='room_key',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
