# Generated by Django 6.0.3 on 2026-04-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_is_online_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
