# Generated by Django 6.0.3 on 2026-04-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
